export const dudeConfigs = {
  left: {
    setVelocityX: -160,
    action: "left",
    weaponPositionX: -12,
    weaponPositionY: 10,
    facing: "left",
    rotation: 0,
    flipX: true,
    visible: true,
  },
  right: {
    setVelocityX: 160,
    action: "right",
    weaponPositionX: 12,
    weaponPositionY: 10,
    facing: "right",
    rotation: 0,
    flipX: false,
    visible: true,
  },
  lookUpLeft: {
    setVelocityX: -160,
    action: "lookUpLeft",
    weaponPositionX: -30,
    weaponPositionY: -20,
    facing: "lookUpLeft",
    rotation: 45,
    flipX: true,
    visible: true,
  },
  lookUpRight: {
    setVelocityX: 160,
    action: "lookUpRight",
    weaponPositionX: 30,
    weaponPositionY: -20,
    facing: "lookUpRight",
    rotation: -45,
    flipX: false,
    visible: true,
  },
  lookUp: {
    setVelocityX: 0,
    action: "lookUp",
    weaponPositionX: 15,
    weaponPositionY: -30,
    facing: "lookUp",
    rotation: -90,
    flipX: false,
    visible: true,
  },
  turn: {
    setVelocityX: 0,
    action: "turn",
    weaponPositionX: 0,
    weaponPositionY: 0,
    facing: "right",
    rotation: 0,
    flipX: false,
    visible: false,
  },
};
